[main]
font=JetBrainsMono Nerd Font:size=8
dpi-aware=auto
terminal=kitty
icons-enabled=no
prompt="> "
width=50
lines=15
anchor=center
use-bold=no
match-mode=fzf
sort-result=yes
match-counter=yes
exit-on-keyboard-focus-loss=yes
minimal-lines=yes

[colors]
background=282828ff
selection=3c3836ff
border=ebdbb2ff
# border=504945ff
text=ebdbb2ff
input=ebdbb2ff
match=fabd2fff
selection-text=ebdbb2ff
prompt=fabd2fff

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=yes
