# path : /etc/samba/smb.conf
#======================= Global Settings =====================================
[global]

# workgroup = NT-Domain-Name or Workgroup-Name, eg: MIDEARTH
   workgroup = WORKGROUP

# server string is the equivalent of the NT Description field
   server string = Samba Server

   server role = standalone server

   log file = /usr/local/samba/var/log.%m

   max log size = 50

   dns proxy = no 


#============================ Share Definitions ==============================
[homes]
   comment = Home Directories
   browseable = yes
   writable = no
